# Generated by Django 3.2.7 on 2021-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211002_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакты'),
        ),
    ]
