# Generated by Django 3.2.7 on 2021-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Картинка'),
        ),
    ]
