# Generated by Django 3.2.7 on 2021-10-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='image_url',
        ),
    ]
